version: "3.8"

services:

 # database service
#  database:
#    image: postgres:15.2
#    environment:
#      POSTGRES_USER: ${DATABASE_USER}
#      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#      POSTGRES_DB: ${DATABASE_NAME}
#      PGDATA: ${DATABASE_PGDATA}
#    volumes:
#      - ${DATABASE_PGDATA}
#    ports:
#      - ${DATABASE_PORT}:${DATABASE_PORT}
#    restart: always
#    networks:
#      - custom
#    env_file:
#      - .env

  # minio service
  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - ${MINIO_PATH_DATA}
    env_file:
      - .env
    command: server --address 0.0.0.0:${MINIO_PORT} --console-address :${MINIO_PORT_2} /data
    ports:
      - ${MINIO_HOST}:${MINIO_PORT}:${MINIO_PORT}
      - ${MINIO_PORT_2}:${MINIO_PORT_2}

  # application service
  fastapi-app:
    build: .
    command: python main.py
    ports:
      - ${SITE_PORT}:${SITE_PORT}
    depends_on:
      - minio
    restart: always
    networks:
      - custom
    env_file:
      - .env

networks:
  custom:
    driver: bridge